export const LOGIN = 'LOGIN'
export const REGISTER = 'REGISTER'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAILED = 'REGISTER_FAILED'
export const REGISTER_FAIL = 'REGISTER_FAIL'
export const USER_LOADED = 'USER_LOADED'
export const AUTH_ERROR = 'AUTH_ERROR'

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILED = 'LOGIN_FAILED'

export const GET_PROFILE = 'GET_PROFILE'
export const PROFILE_ERROR = 'PROFILE_ERROR'
export const CLEAR_PROFILE = 'CLEAR_PROFILE'

export const LOGOUT = 'LOGOUT'
export const LOADING = 'LOADING'

export const SET_ALERT_REGISTER = 'SET_ALERT_REGISTER'
export const SET_ALERT_LOGIN = 'SET_ALERT_LOGIN'
export const RESET_ALERT = 'RESET_ALERT'
export const SET_ALERT = 'SET_ALERT'